services:
  app:
    build:
        context: .
        dockerfile: docker/php/Dockerfile
    container_name: laravel_api
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE:
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
